name: Continuous integration
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16.x

      - name: Lint and build extension
        run: |
          npm install
          npm run lint
          npm run package -- --out godot-tools.vsix
          ls -l godot-tools.vsix

      - name: Upload extension VSIX
        uses: actions/upload-artifact@v2
        with:
          name: godot-tools
          path: godot-tools.vsix
